version: "3"

services:  
  api-gympass-pg:
    image: bitnami/postgresql
    ports: 
      - 5441:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apigympass